import { User } from '@app/users/models/user';
export const users: Array<User> = [
  {
    id: '1',
    photo: '/www/upeterson.jpg',
    externalId: 'CA47-1067-B31D-00DD01066201',
    orderNo: 1,
    url: '',
    userName: 'upeterson',
    firstName: 'User',
    lastName: 'Peterson',
    iconUrl: '',
    email: 'upeterson@state.gov',
    description: 'nice guy',
    longDescription: 'sometimes not as nice',
    userType: 'employee',
  },
  {
    id: '5',
    photo: '/www/srogers.jpg',
    externalId: 'CA47-1067-B31D-00DD01066202',
    orderNo: 3,
    url: '',
    userName: 'srogers',
    firstName: 'Sam',
    lastName: 'Rogers',
    iconUrl: '',
    email: 'srogers@amazon.com',
    description: '',
    longDescription: '',
    userType: 'employee',
  },
  {
    id: '3',
    photo: '/www/srogers.jpg',
    externalId: 'CA47-1067-B31D-00DD01066203',
    orderNo: 2,
    url: '',
    userName: 'scarlsman',
    firstName: 'Sean',
    lastName: 'Carlsman',
    iconUrl: '',
    email: '',
    description: '',
    longDescription: '',
    userType: 'security',
  },
  {
    id: '2',
    photo: '/www/mchoi.jpg',
    externalId: 'CA47-1067-B31D-00DD01066204',
    orderNo: 9,
    url: '',
    userName: 'mchoi',
    firstName: 'Marry',
    lastName: 'Choi',
    iconUrl: '',
    email: '',
    description: '',
    longDescription: '',
    userType: 'security',
  },
  {
    id: '11',
    photo: '/www/landerson.jpg',
    externalId: 'CA47-1067-B31D-00DD01066205',
    orderNo: 8,
    url: '',
    userName: 'landerson',
    firstName: 'Larry',
    lastName: 'Anderson',
    iconUrl: '',
    email: '',
    description: '',
    longDescription: '',
    userType: 'security',
  },
  {
    id: '5',
    photo: '/www/rmaya.jpg',
    externalId: 'CA47-1067-B31D-00DD01066206',
    orderNo: 5,
    url: '',
    userName: 'rmaya',
    firstName: 'Rhea',
    lastName: 'Maya',
    iconUrl: '',
    email: '',
    description: '',
    longDescription: '',
    userType: 'security',
  },
  {
    id: '4',
    photo: '/www/kolson.jpg',
    externalId: 'CA47-1067-B31D-00DD01066207',
    orderNo: 4,
    url: '',
    userName: 'kolson',
    firstName: 'Kate',
    lastName: 'Olson',
    iconUrl: '',
    email: '',
    description: '',
    longDescription: '',
    userType: 'Owner',
  },
];
